services:
  attendance-app:
    build: .
    image: attendance-report
    container_name: attendance_container
    volumes:
      - "./samples/input:/data/input"
      - "./output:/output"
    environment:
      - TESSERACT_CMD=/usr/bin/tesseract
    command: ["/data/input/sample_report_a.pdf", "-o", "/app/output"]
