services:
  attendance-app:
    build: .
    image: attendance-report
    container_name: attendance_container
    volumes:
      - "D:/input_pdfs:/data/input"
      - "./output:/app/output"
    environment:
      - TESSERACT_CMD=/usr/bin/tesseract
    command: ["/data/input/a_r_25.pdf", "-o", "/app/output"]